controllers:
    resource: ../src/Controller/
    type: attribute
app_entreprise_new:
    path: /entreprise/new
    controller: App\Controller\EntrepriseController::new
app_entreprise_edit:
    path: /entreprise/edit
    controller: App\Controller\EntrepriseController::edit
app_entreprise_list:
    path: /entreprise/list
    controller: App\Controller\EntrepriseController::list
